language: java

jdk:
  - oraclejdk8

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew test --console=plain --info
  - ./gradlew jacocoTestReport

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -s https://codecov.io/bash)
